name: Question
description: Ask about architecture, behavior, or usage.
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Your question
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Relevant files, endpoint, logs, screenshots.
